AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Parameters:
  DynamoDbEndpoint:
    Type: String
    Description: Dynamo db endpoint
    Default: http://host.docker.internal:8000
  WebClientOrigin:
    Type: String
    Description: Web app origin
    Default: https://localhost:1234
Description: >
  open-kitch-app

Globals:
  Function:
    Timeout: 3
    MemorySize: 512
  Api:
    Cors:
      AllowOrigin: !Join
        - ""
        - - "'"
          - !Ref WebClientOrigin
          - "'"
      AllowMethods: "'*'"
      AllowHeaders: "'*'"

Resources:
  MenuFunctions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: menu/dist
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: !Ref DynamoDbEndpoint
          WEB_CLIENT_ORIGIN: !Ref WebClientOrigin
      Events:
        GetMenuItems:
          Type: Api
          Properties:
            Path: /kitchens/{kitchenId}/menuItems
            Method: get
        PutMenuItem:
          Type: Api
          Properties:
            Path: /kitchens/{kitchenId}/menuItems/{menuItemId}
            Method: put
